language: rust
rust:
- nightly
- beta
- stable
addons:
  postgresql: 9.4
before_script:
- "git clone https://github.com/ivanceras/rustorm ../rustorm"
- "./scripts/setup.sh"

after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make &&
  sudo make install && cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/codegenta-*

script:
- cargo test


