[package]
name = "codegenta"
version = "0.0.2"
authors = [ "Jovansonlee Cesar <ivanceras@gmail.com>" ]
license = "MIT"
description = "A model code generator from database table using rustorm ORM"
readme = "README.md"
repository = "https://github.com/ivanceras/codegenta"
documentation = "https://ivanceras.github.io/codegenta/codegenta/"
keywords = ["orm", "codegen", "generator", "database"]

[lib]
name = "codegenta"

#[dependencies.rustorm]
#git = "https://github.com/ivanceras/rustorm"


[dependencies.rustorm]
path = "../rustorm"

[dependencies.chrono]
version = "*"
features = ["rustc-serialize"]

[dependencies]
rustc-serialize = "*"
uuid = "*"
time = "*"
#rustorm ="*"
